# _config.yml
title: "Rathin’s corner"
description: "Experiments, notes and projects."

plugins:
  - jekyll-feed
  - jekyll-seo-tag     # optional—keep if you want it
  - jekyll-archives

sass:
  style: compressed    # keep CSS tiny

collections:
  research:
    output: true
    permalink: /_research/:slug/
  notes:
    output: true
    permalink: /_notes/:slug/  

jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: archive
    tag: archive  

excerpt_separator: "<!--more-->"
    
