# _config.yml
title: "Rathin’s corner"
description: "Experiments, notes and projects."

plugins:
  - jekyll-feed
  - jekyll-seo-tag     # optional—keep if you want it

sass:
  style: compressed    # keep CSS tiny
