# Site settings
title: "Rathin’s corner"
description: "Experiments, notes and projects."
theme: minima

# Plugins to keep the build fast & SEO friendly
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Tell Jekyll to process our custom SASS
sass:
  sass_dir: _sass
  style: compressed

# Navigation menu (inline, right‑aligned)
nav:
  - title: "Welcome!"
    url: "/"
  - title: "CV"
    url: "/cv/"
  - title: "Probability & Statistics"
    url: "/research/probability-statistics/"
  - title: "Machine Learning"
    url: "/research/machine-learning/"
  - title: "Quantum Probability"
    url: "/research/quantum-probability/"
  - title: "Financial Mathematics"
    url: "/research/financial-mathematics/"
  - title: "Automated Theorem Proving"
    url: "/research/automated-theorem-proving/"
